### ISSUE TITLE
Do not package logs (reduce the unpacked size more than 5300 times) 

### ISSUE THREAD

**Issue by ChALkeR** [peerigon/servus.js#3]
_Disclaimer: I do not use the package, this was found during automated npm packages downloading._

Atm, your npm package `servus.js@0.0.1` has packaged size **5.11 MiB**, and installed size **122.79 MiB**.

**122.77 MiB** (99.98%) of that is consumed by the `log.jtl` file, which looks like a some http requests log file.

I suspect that that file was accidently packaged.

You could add it to `.npmignore` (if you have an `.npmignore` already) or to `.gitignore` (if you don't have an `.npmignore`).

---

Your current package files (as of `servus.js@0.0.1`):

```
servus.js-0.0.1.tgz/
├── app.js
├── fig.yml
├── lib
│   └── servus.js
├── LICENSE
├── log.jtl
├── .npmignore
├── package.json
├── README.md
├── Servus.jmx
├── test
│   └── servus.test.js
├── .travis.yml
└── Vagrantfile

2 directories, 12 files
```

**Comment by matthaias** [comment]
Thx, should be solved with version 0.0.2.

> ➜  servusjs  npm ls servus.js
> /Users/peerigon/test/servusjs
> └── servus.js@0.0.2
> 
> ➜  servusjs  tree
> .
> └── node_modules
>     └── servus.js
>         ├── LICENSE
>         ├── README.md
>         ├── Servus.jmx
>         ├── Vagrantfile
>         ├── app.js
>         ├── fig.yml
>         ├── lib
>         │   └── servus.js
>         ├── package.json
>         └── test
>             └── servus.test.js
> 
> 4 directories, 9 files
